# Project: 项目5
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = 项目5_private.res
OBJ      = TItle.o $(RES)
LINKOBJ  = TItle.o $(RES)
LIBS     = -L"C:/linchenbang/Dev-Cpp/MinGW64/lib" -L"C:/linchenbang/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/linchenbang/Dev-Cpp/MinGW64/include" -I"C:/linchenbang/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/linchenbang/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/linchenbang/Dev-Cpp/MinGW64/include" -I"C:/linchenbang/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/linchenbang/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/linchenbang/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 项目5.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

TItle.o: TItle.cpp
	$(CPP) -c TItle.cpp -o TItle.o $(CXXFLAGS)

项目5_private.res: 项目5_private.rc 
	$(WINDRES) -i 项目5_private.rc --input-format=rc -o 项目5_private.res -O coff 

